// LivePreview.jsx — Live Demo через StackBlitz WebContainers
// Приймає масив файлів { path, content } і відкриває живий проєкт в iframe

import { useState, useEffect, useRef } from 'react'

const B = '#BECAE1', SD = '#a0b3cb', SL = '#d6e4f7', T = '#3a4a5c', AC = '#5b8fc9', GR = '#6bab8e'
const neu = (i = false) => i ? `inset 4px 4px 10px ${SD},inset -4px -4px 10px ${SL}` : `6px 6px 14px ${SD},-6px -6px 14px ${SL}`

// Визначаємо тип проєкту за файлами
function detectProjectType(files) {
  const paths = files.map(f => f.path)
  if (paths.some(p => p.includes('package.json'))) return 'node'
  if (paths.some(p => p.endsWith('.html'))) return 'html'
  return 'html'
}

// Для HTML проєктів — збираємо srcdoc inline (без зовнішніх запитів)
function buildSrcdoc(files) {
  const html = files.find(f => f.path === 'index.html' || f.path.endsWith('/index.html'))
  const cssFiles = files.filter(f => f.path.endsWith('.css'))
  const jsFiles = files.filter(f => f.path.endsWith('.js') && !f.path.includes('node_modules') && !f.path.includes('vite') && !f.path.includes('sw'))

  if (!html) {
    // Якщо немає HTML — показуємо першый CSS/JS файл як code
    const cssContent = cssFiles.map(f => f.content).join('\n')
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
      body{background:#1a2840;color:#a8d4c8;font-family:monospace;padding:24px}
      pre{white-space:pre-wrap;word-break:break-word;font-size:13px;line-height:1.6}
    </style></head><body><pre>${cssContent.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre></body></html>`
  }

  let doc = html.content

  // Інжектуємо CSS inline
  const cssInline = cssFiles.map(f => `<style>/* ${f.path} */\n${f.content}</style>`).join('\n')
  doc = doc.replace('</head>', `${cssInline}\n</head>`)

  // Інжектуємо JS inline (тільки vanilla JS, не модулі)
  const jsInline = jsFiles
    .filter(f => !f.content.includes('import ') && !f.content.includes('export '))
    .map(f => `<script>/* ${f.path} */\n${f.content}</script>`)
    .join('\n')
  doc = doc.replace('</body>', `${jsInline}\n</body>`)

  return doc
}

// Для React/Node проєктів — відкриваємо StackBlitz
async function openStackBlitz(files, projectName) {
  try {
    // Динамічний імпорт StackBlitz SDK
    const sdk = await import('https://unpkg.com/@stackblitz/sdk@1/bundles/sdk.m.js')

    // Конвертуємо масив файлів у об'єкт { path: content }
    const filesObj = {}
    files.forEach(({ path, content }) => { filesObj[path] = content })

    return sdk.default.openProject({
      title: projectName,
      description: 'Generated by PWA Dev Agent',
      template: 'node',
      files: filesObj,
      settings: { compile: { trigger: 'auto' } },
    })
  } catch (err) {
    console.warn('StackBlitz SDK failed:', err)
    return null
  }
}

export function LivePreview({ files, projectName, onClose }) {
  const [mode, setMode] = useState('loading') // loading | iframe | stackblitz | error
  const [srcdoc, setSrcdoc] = useState('')
  const [sbLoading, setSbLoading] = useState(false)
  const iframeRef = useRef(null)

  const projectType = detectProjectType(files)
  const isHtml = projectType === 'html'

  useEffect(() => {
    if (isHtml) {
      const doc = buildSrcdoc(files)
      setSrcdoc(doc)
      setMode('iframe')
    } else {
      setMode('stackblitz')
    }
  }, [files, isHtml])

  const handleStackBlitz = async () => {
    setSbLoading(true)
    await openStackBlitz(files, projectName)
    setSbLoading(false)
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(130,150,175,0.55)', backdropFilter: 'blur(8px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 999, padding: 16, fontFamily: "'DM Sans', sans-serif" }}>
      <div style={{ background: B, borderRadius: 24, boxShadow: `14px 14px 32px ${SD},-14px -14px 32px ${SL}`, width: 'min(900px,98vw)', height: 'min(640px,90vh)', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

        {/* Header */}
        <div style={{ padding: '13px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: `1px solid ${SD}`, flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 20 }}>▶</span>
            <div>
              <div style={{ fontWeight: '700', fontSize: 15, color: T }}>{projectName}</div>
              <div style={{ fontSize: 11, color: '#7a90a8', marginTop: 1 }}>
                {isHtml ? 'HTML/CSS · inline preview' : 'React/Node · StackBlitz WebContainer'}
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 9 }}>
            {/* Для React проєктів — кнопка StackBlitz */}
            {!isHtml && (
              <button onClick={handleStackBlitz} disabled={sbLoading}
                style={{ background: B, border: 'none', borderRadius: 10, padding: '7px 14px', fontSize: 12, fontWeight: '700', color: sbLoading ? '#7a90a8' : '#1374ef', boxShadow: sbLoading ? neu(true) : neu(), cursor: sbLoading ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', gap: 6 }}>
                {sbLoading ? '⏳ Завантаження...' : '⚡ Відкрити в StackBlitz'}
              </button>
            )}
            {/* Для HTML — refresh */}
            {isHtml && (
              <button onClick={() => { const d = buildSrcdoc(files); setSrcdoc(''); setTimeout(() => setSrcdoc(d), 50) }}
                style={{ background: B, border: 'none', borderRadius: 10, padding: '7px 12px', fontSize: 13, color: '#7a90a8', boxShadow: neu(), cursor: 'pointer' }}>
                ↺
              </button>
            )}
            <button onClick={onClose}
              style={{ background: B, border: 'none', borderRadius: '50%', width: 34, height: 34, cursor: 'pointer', boxShadow: neu(), color: T, fontSize: 15, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              ✕
            </button>
          </div>
        </div>

        {/* Content */}
        <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>

          {/* HTML inline preview */}
          {mode === 'iframe' && srcdoc && (
            <iframe
              ref={iframeRef}
              srcDoc={srcdoc}
              sandbox="allow-scripts allow-same-origin"
              style={{ width: '100%', height: '100%', border: 'none', borderRadius: '0 0 24px 24px' }}
              title="Live Preview"
            />
          )}

          {/* React/Node — пропозиція StackBlitz */}
          {mode === 'stackblitz' && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 20, padding: 32 }}>
              <div style={{ fontSize: 48 }}>⚡</div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontWeight: '700', fontSize: 17, color: T, marginBottom: 8 }}>React/Node проєкт</div>
                <div style={{ fontSize: 13, color: '#7a90a8', lineHeight: 1.6, maxWidth: 360 }}>
                  Цей проєкт потребує Node.js середовища.<br />
                  StackBlitz WebContainers запустить його прямо у браузері — без встановлення.
                </div>
              </div>
              <button onClick={handleStackBlitz} disabled={sbLoading}
                style={{ background: B, border: 'none', borderRadius: 14, padding: '12px 28px', fontSize: 15, fontWeight: '700', color: '#1374ef', boxShadow: sbLoading ? neu(true) : neu(), cursor: sbLoading ? 'not-allowed' : 'pointer' }}>
                {sbLoading ? '⏳ Відкриття...' : '⚡ Запустити в StackBlitz'}
              </button>
              <div style={{ fontSize: 11, color: '#9ab5cc' }}>Відкриється у новій вкладці</div>
            </div>
          )}

          {mode === 'loading' && (
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
              <div style={{ fontSize: 13, color: '#7a90a8' }}>Підготовка preview...</div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
